<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework</span></h1>
    <?php
    $title = 'My posts';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('post', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>description</th>
    <th>category</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($posts as $post) : ?>
    <tr>
        <td><?= $this->escapeHtml($post->getTitle()) ?></td>
        <td><?= $this->escapeHtml($post->getDescription()) ?></td>
        <td><?= $this->escapeHtml($post->getCategory()) ?></td>
        <td>
            <a href="<?= $this->url('post', ['action' => 'edit', 'id' => $post->getId()]) ?>">Edit</a>
            <a href="<?= $this->url('post', ['action' => 'delete', 'id' => $post->getId()]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
</div>
